# Generated by Django 5.1.2 on 2025-01-30 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prendas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='prenda',
            table='prendas',
        ),
    ]
