# Generated by Django 5.1.2 on 2025-01-30 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prendas', '0002_alter_prenda_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='prenda',
            table='prendas_prenda',
        ),
    ]
