# Generated by Django 5.1.2 on 2025-01-30 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prendas', '0005_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
    ]
