# Generated by Django 5.1.2 on 2025-02-09 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prendas', '0006_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='descripcion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterModelTable(
            name='categoria',
            table=None,
        ),
    ]
