# Generated by Django 5.1.2 on 2025-02-11 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prendas', '0009_testimonio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alquiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('estado', models.CharField(default='activo', max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('prenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prendas.prenda')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prendas.usuario')),
            ],
            options={
                'db_table': 'alquiler',
            },
        ),
    ]
